version: '3.8'
services:
  mongo:
    build: .
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=testdb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/testdb --quiet
      interval: 7s
      timeout: 20s
      retries: 5
  mongo-express:
    build: .
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8888:8081"
  redis:
    build: .
    image: "redis:latest"
    restart: always
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis-password}
    command: redis-server --save 20 1 --loglevel warning
#    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redis-password}
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local

networks:
  default:
    name: mongodb_network
