server:
  port: 9081
spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema.registry.url: "http://localhost:8081"
        value:
          subject:
            name:
              strategy: "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      group-id: "avro-kafka-group-id"
      auto-offset-reset: "earliest"
      properties:
        schema.registry.url: "http://localhost:8081"
        specific.avro.reader: true
        value:
          subject:
            name:
              strategy: "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy"
avro:
  topic:
    name: "avro-test-topic"
