server:
  port: 8000

spring:
  data:
    mongodb:
      authentication-database: admin
      username: devroot
      password: devroot
      database: testdb
      port: 27017
      host: localhost
      auto-index-creation: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
#      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
  redis:
    host: localhost
    port: 6379
    database: 0
#    username: default
#    password: redis-password
    timeout: 60000
    io-thread-pool-size: 10
    computation-thread-pool-size: 10
    cache:
      expiration-after-write-policy: 1h
    pool:
      enabled: true
      min-idle: 5
      max-total: 15
      max-idle: 10

