server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: hello
          uri: lb://eclient
          predicates: Path=/one/**
        - id: buy
          uri: lb://eclient-2
          predicates: Path=/two/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

