server:
  port: 8001
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:h2:mem:jwtdemodb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
log4j:
  logger:
    org:
      hibernate:
        SQL: debug
        type: trace

jwt:
  secret: asdfghjhmgfdsadfg
  accessExpirationTimeMs: 120000

#management:
#  security:
#    enabled: false