server:
  port: 8001
spring:
  kafka:
    bootstrap-servers: localhost:9092
    topic: test.manual
    topic-entity: topic-entity
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false